package com.realtimebid.auction;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.hibernate.annotations.CreationTimestamp;

import com.realtimebid.user.User;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Version;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/*
 * @Entity
 * Marks this class as a JPA entity.
 *
 * Hibernate will map this Java class to a database table.
 *
 * Java:
 * Auction
 *
 * Database:
 * auctions
 */
@Entity

/*
 * Explicitly specifies the database table name.
 */
@Table(name = "auctions")

/*
 * Lombok generates getters and setters automatically.
 *
 * We use @Getter and @Setter instead of @Data because we don't necessarily want
 * all the extra methods generated by @Data such as equals(), hashCode() and
 * toString().
 */
@Getter
@Setter

/*
 * Generates a no-argument constructor.
 *
 * JPA requires a no-argument constructor to create entity objects when
 * retrieving records from the database.
 */
@NoArgsConstructor
public class Auction {

	/*
	 * Primary key of the auction table.
	 */
	@Id

	/*
	 * The database automatically generates the ID whenever a new auction is
	 * inserted.
	 *
	 * Example:
	 *
	 * Auction 1 -> id = 1 Auction 2 -> id = 2
	 */
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	/*
	 * Title of the auction.
	 *
	 * Example: "Apple MacBook Pro M4"
	 */
	@Column
	private String title;

	/*
	 * Detailed information about the item being auctioned.
	 *
	 * Example: "MacBook Pro M4, 16GB RAM, 512GB SSD..."
	 */
	@Column
	private String description;

	/*
	 * Initial price from which the auction starts.
	 *
	 * BigDecimal is used instead of double/float because this field represents
	 * money.
	 *
	 * precision = 10 -> Maximum total number of digits.
	 *
	 * scale = 2 -> Maximum 2 digits after the decimal point.
	 *
	 * Example: 99999.99
	 */
	@Column(precision = 10, scale = 2)
	private BigDecimal startingPrice;

	/*
	 * Minimum price that the seller is willing to accept.
	 *
	 * This is commonly called the "reserve price".
	 *
	 * Example:
	 *
	 * Starting price = ₹10,000 Reserve price = ₹15,000
	 *
	 * If the auction ends at ₹12,000, the reserve price has not been reached.
	 */
	@Column(precision = 10, scale = 2)
	private BigDecimal reservePrice;

	/*
	 * Date and time when the auction becomes active.
	 *
	 * Example: 2026-10-01 10:00 AM
	 */
	@Column
	private LocalDateTime startTime;

	/*
	 * Date and time when the auction ends.
	 *
	 * After this time, new bids should not be accepted.
	 */
	@Column
	private LocalDateTime endTime;

	/*
	 * Represents the current state of the auction.
	 *
	 * Example values could be:
	 *
	 * UPCOMING ACTIVE ENDED SCHEDULED
	 *
	 * @Enumerated(EnumType.STRING) stores the enum name as text in the database.
	 *
	 * Example: ACTIVE
	 *
	 * instead of: 1
	 */
	@Enumerated(EnumType.STRING)
	private AuctionStatus status;

	/*
	 * Many auctions can belong to one seller.
	 *
	 * Example:
	 *
	 * User A ├── Auction 1 ├── Auction 2 └── Auction 3
	 *
	 * Therefore: Many Auctions -> One User
	 */
	@ManyToOne

	/*
	 * Creates the foreign-key column in the auctions table.
	 *
	 * seller_id will contain the ID of the User who created the auction.
	 *
	 * Example:
	 *
	 * auctions -------------------------------- id | title | seller_id 1 | Laptop|
	 * 5
	 *
	 * seller_id = 5 refers to User with id = 5.
	 *
	 * nullable = false means every auction must have a seller.
	 */
	@JoinColumn(name = "seller_id", nullable = false)
	private User seller;

	/*
	 * @Version is used for optimistic locking.
	 *
	 * This is especially important for RealTimeBid because multiple users may
	 * interact with auction data at nearly the same time.
	 *
	 * Hibernate automatically increases this value when the entity is updated.
	 *
	 * Example:
	 *
	 * Auction version = 1
	 *
	 * Two requests read version 1.
	 *
	 * Request A updates the auction first. Version becomes 2.
	 *
	 * Request B tries to update using the old version 1. Hibernate detects the
	 * conflict and prevents the stale update.
	 */
	@Version
	private Long version;

	/*
	 * Automatically stores the date and time when the auction record is created.
	 *
	 * We don't need to manually set this value.
	 */
	@CreationTimestamp
	private LocalDateTime createdAt;
}